### ISSUE TITLE
Dúvidas na utilização

### ISSUE THREAD

**Issue by henriqueneves** [wmixlabs/bradesco-boleto-registro#1]
Olá!
Pelo que eu vi o código de vocês é bem elaborado e completo. Caso eu consiga utiliza-lo corretamente, pretendo elaborar uma documentação para ajudar outros novatos nessa área de comunicação com a API do Bradesco.

Meu objetivo:
-Registrar os boletos no Bradesco (apenas!);

Questões)
1) Coloquei no RegistroEntradaBoleto os dados referente ao meu boleto. Em seguida estou tentando simular o envio. Seria basicamente isso?

```
        WSRegistroBoleto registro = new WSRegistroBoleto();
        registro.enviarBoleto(new BBRConfigPersonalizado(), new RegistroEntradaBoleto());
```

Só preciso fazer isso para enviar?

Minhas maiores dúvidas estão no BBRConfig():
2) Onde consigo o certificado requisitado pelo método getCertificadoKeyStore()? Que formato é esse arquivo? Pego no Bradesco Net Empresas?

3) Se eu abrir esse arquivo encontrarei a senha requisitada no método getCertificadoSenha()?

4) getCadeiaCertificadosKeyStore() é obrigatório? Onde consigo a senha do exemplo?
`FileUtils.writeByteArrayToFile(new File("/tmp/producao.cacerts"), NFGeraCadeiaCertificados.geraCadeiaCertificados(NFAmbiente.PRODUCAO, "senha"));`

Obrigado e desculpe as possíveis perguntas bobas. Sou extremamente leigo nisso!

**Comment by fincatto** [comment]
O certificado é o certificado A1 da empresa, necessário para assinar os requests que serão enviados ao banco (similar a NFe). Você consegue um em qualquer empresa certificadora (Correios, CDL, etc).

A cadeia de certificados, também similar ao NFe, é a cadeia que seu sistema vai confiar, evitando ataques do tipo "Man In The Middle". Esse é mais facil, você pode gerar um novo usando essa classe pra gerar o certificado e usar a senha que quiser.
